modules:
    - imsim

template: imsim-config-skycat

input.sky_catalog.obj_types: [stars]

# Disable the atmospheric PSF
input.atm_psf: ""
psf:
    type: Convolve
    items:
        -
           type: Gaussian
           fwhm: 0.8
        -
           type: Gaussian
           fwhm: 0.3

input.checkpoint: ""  # Turn off check pointing
input.sky_catalog.file_name: /sdf/home/j/jchiang/dev/imSim/tests/data/sky_cat_9683.yaml
input.opsim_data.file_name: calib_frames.db
input.opsim_data.visit: 4000000

image.nobjects: 0
image.sky_level: 0
image.apply_sky_gradient: False
image.apply_fringing: False
image.random_seed: ""

output.dir:
    type: FormattedStr
    format: calib_frames/%08d
    items:
        - "@input.opsim_data.visit"
output.det_num.first: 4
output.nproc: 1
output.nfiles: 2
output.camera: LsstComCamSim
output.truth: ""
output.readout.added_keywords: {'IMGTYPE': 'dark', 'REASON': 'dark',
                                'OBSTYPE': 'calibration', 'PROGRAM': 'calibration'}

output.readout.file_name:
    type: FormattedStr
    format : dark_%08d-%1d-%s-%s-det%03d.fits.fz
    items:
        - { type: OpsimData, field: observationId }
        - { type: OpsimData, field: snap }
        - "$band"
        - "$det_name"
        - "@output.det_num"
